---
title: "Visualizations for article"
author: "Lincoln Mullen"
date: "November 3, 2015"
output: html_document
---

```{r message=FALSE}
library("readr")
library("igraph")
library("dplyr")
library("stringr")
library("parallel")
library("textreuse")
source("R/best-section-matches.R")
source("R/summarize-borrowings.R")
source("R/extract-date.R")
source("R/extract_code_names.R")
options("mc.cores" = 6L)
```

Read the data.

```{r}
load("cache/corpus-lsh.rda")
codes <- c(scores$code_a, scores$code_b) %>% unique()
```

Calculate section matches and summarize them for a single code.

```{r}
CA1851 <- best_section_matches("CA1851", scores, threshold = 0.15)
CA1851
summarize_borrowings(CA1851)
```

Apply that to all the codes.

```{r}
code_match_summary <- codes %>% 
  mclapply(best_section_matches, scores = scores, threshold = 0.15)  %>% 
  mclapply(summarize_borrowings) %>% 
  bind_rows()
code_match_summary
```

Create a network graph based on section percentages.

```{r}
edges_pct <-
  code_match_summary %>% 
  mutate(borrower_date = extract_date(borrower_code),
         match_date = extract_date(match_code)) %>% 
  filter(percentage_sections >= 0.05,
         !is.na(match_code),
         borrower_date >= match_date) %>% 
  select(borrower_code, match_code, weight = percentage_sections) %>% 
  group_by(borrower_code) %>% 
  top_n(2, weight)
edges_pct

g <- graph_from_data_frame(edges_pct, directed = TRUE) 
nodes <- distances(g, to = "NY1850", algorithm = "unweighted") %>% as.data.frame() %>% 
  add_rownames() %>% 
  rename(name = rowname, distance = NY1850) %>% 
  mutate(color = ifelse(distance == 0, "red",
                        ifelse(distance == 1, "green",
                               ifelse(distance == 2, "yellow", "lightblue"))))

nodes[nodes$name == "NY1848", "color"] <- "red"
nodes[nodes$name == "NY1849", "color"] <- "red"
nodes[nodes$name == "NY1850", "color"] <- "red"
nodes[nodes$name == "NY1851", "color"] <- "red"
g <- graph_from_data_frame(edges_pct, directed = TRUE, vertices = nodes) 
V(g)$year <- V(g)$name %>% extract_date()
set.seed(4221)

g <- add_layout_(g, with_graphopt(niter = 4000, spring.length = 25), normalize())

plot_before_year <- function(x, year) {
  x_before <- induced.subgraph(x, which(V(x)$year <= year))
  n <- V(x)$name
  n_before <- V(x_before)$name
  filter <- n %in% n_before
  x_before$layout <- x_before$layout[filter, ]
  par(mar = c(0,0,1,0))
  plot(x_before, edge.width = E(x_before)$weight * 8,
       edge.arrow.size = 0.0, vertex.size = 5)
  title(paste0("Codes of Civil Procedure before ", year))
} 

for (i in seq(1850, 1900, 5)) {
  png(filename = paste0("out/field-code-network-ALL", i, ".png"), width = 1200,
      height = 900)
  plot_before_year(g, i)
  dev.off()
}
```

