---
title: "The Migration of the Field Code"
author: "Kellen Funk and Lincoln Mullen"
---

This is an analysis notebook for detecting text reuse in legal codes of civil procedure---the "Field codes"---in the nineteenth-century United States. It is a collaboration between [Kellen Funk](http://kellenfunk.org/) and [Lincoln Mullen](http://lincolnmullen.com). This [working paper](talks/dh-working-group/Funk-Mullen.Migration-Field-Code.working-paper.pdf) has the most up-to-date summary of what we are doing.

See these links for more details:

- [Kellen's posts about the project](http://kellenfunk.org/field-code/)
- [An Introduction to the textreuse Package, with Suggested Applications](http://lincolnmullen.com/blog/an-introduction-to-the-textreuse-package/)
- [Detecting Text Reuse in Nineteenth-Century Legal Documents](http://lincolnmullen.com/blog/detecting-text-reuse-in-legal-documents/)

You may also be interested in the materials for various talks we have given about this project.

- [AHA 2016 lightening talk slides](talks/aha2016/aha2016.html)
- Digital Humanities Working Group, George Mason University: [paper](talks/dh-working-group/Funk-Mullen.Migration-Field-Code.working-paper.pdf), [slides](talks/dh-working-group-slides/dh-working-group-slides.html)

This notebook contains our work in progress. This is the most recent analysis in progress. There is more in the [repository](https://github.com/lmullen/civil-procedure-codes).

```{r echo=FALSE, results='asis'}
rmd <- Sys.glob("*.Rmd")
rmd <- rmd[!rmd %in% c("index.Rmd", "article.Rmd")]
html <- sub(".Rmd", ".html", rmd)
lines <- lapply(rmd, readLines)
yaml <- lapply(lines, rmarkdown:::parse_yaml_front_matter)
cat("<ul>")
for (i in seq_along(rmd)) {
  cat(paste0("<li><a href='", html[i], "'>", yaml[[i]]$title, "</a><br/>",
             "<code>", rmd[i], "</code>", "</li>"))
}
cat("</ul>")
```

