---
title: "Network Analysis of Code Similarity"
author: "Kellen Funk and Lincoln Mullen"
date: "November 21, 2014"
output: html_document
---

```{r echo=FALSE}
packrat::on()
library(magrittr)
library(RWeka)
library(stringi)
library(igraph)
source("R/helper.R")

# Load the data if it doesn't exist already.
if(file.exists("out/codes.rda")) {
  load("out/codes.rda")
  } else {
  source("R/load-data.R")
  save(codes, file = "out/codes.rda")
  }
```

There are the codes that we currently have:

```{r}
names(codes)
```

Create the comparison matrix:

```{r}
cf <- outer_for_lists(codes, codes, compare_codes_by_shared_ngrams)
```

Remove obviously incorrect values:

```{r}
cf2  <- cf
diag(cf2) <- NA                 # remove codes compared to themselves
cf2 <- rm_anachronism(cf2)       # remove anachronistic comparisons

significance_threshold <- 0.03
cf2[cf2 < significance_threshold] <- NA
cf2[is.na(cf2)] <- 0
```

Now we can create a graph object from the comparison matrix, which we will treat as an adjacency matrix.

```{r}
g <- graph.adjacency(cf2, mode = "directed", weighted = TRUE, diag = FALSE) 
set.seed(4821)
l <- layout.fruchterman.reingold(g, weights = E(g)$weight)
par(mar=c(0,0,1,0))
plot(g, edge.width = E(g)$weight * 10, layout = l,
     edge.arrow.size= 0.15, vertex.size = 5)
title("Codes of Civil Procedure")
```

Community detection

```{r}
g %>%
  walktrap.community() %>%
  plot(., g, vertex.label = NA, layout = l, vertex.size = 3)
```


Get just the component graphs

```{r}
sub <- decompose.graph(g, mode = "weak", min.vertices = 3)[[1]]
l2 <- layout.fruchterman.reingold(sub, weights = E(sub)$weight)
par(mar=c(0,0,1,0))
plot(sub, edge.width = E(sub)$weight * 10, layout = l2,
     edge.arrow.size= 0.15, vertex.size = 5)
title("Largest family of codes")
```

Neighborhood of NY 1850

```{r}
ny <- which(V(g)$name == "IA851")
neighbors(g, ny)
graph.neighborhood(g, order = 1, nodes = ny)[[1]] %>%
  plot_graph()
```

Get all the influences for people who need words.

```{r}
influences <- colnames(cf2) %>%
  lapply(., function(name) { get_influences(cf2, name, 10) })
names(influences) <- colnames(cf2)
print(influences)
```


